services:
  - type: web
    name: hospital-it-helpdesk-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
        placeholder: "Your MongoDB connection URI (e.g. MongoDB Atlas link)"
      - key: CLIENT_URL
        sync: false
        placeholder: "Your Netlify site URL (e.g. https://rainbow-klepon-f379d7.netlify.app)"
